version: '3.8'

services:
  backend:
    build: .
    container_name: fastapi_backend
    ports:
      - "8000:8000"
      - "3478:3478/udp"  # WebRTC STUN/TURN communication
      - "10000-10100:10000-10100/udp"  # WebRTC media ports
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
